# Use this one instead
# https://medium.com/@bjnandi/containerize-your-full-stack-web-application-mern-with-docker-compose-4900156ba9dd#:~:text=For%20the%20dockerize%20a%20full,yml%20file.

# version: '3.8'

# Services
services:
  # Server service
  server:
    build:
      context: ./grid-backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8082:8082"
    env_file: ./.env
    environment:
      # - DB_HOST=mongodb_server
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      # - DB_NAME=$MONGODB_DATABASE
      # - DB_PORT=$MONGODB_DOCKER_PORT
    depends_on:
      - mongodb

  # Client service
  client:
    build:
      context: ./react-grid-vite-test1
      dockerfile: Dockerfile

    container_name: frontend
    ports:
      - "80:80"
    env_file: ./react-grid-vite-test1/.env  # Reference the specific .env file
    depends_on:
      - server

  # Widget service
  widget:
    build:
      context: ./python-flask
      dockerfile: Dockerfile
      
    container_name: python-flask
    ports:
      - "3001:3001"
    depends_on:
      - mongodb

  # Database service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server

    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD

    ports:
      - "27017:27017"

    volumes:
      - ./data:/data/db

# Volumes define
# volumes: 
#   mydata: