# Use this one instead
# https://medium.com/@bjnandi/containerize-your-full-stack-web-application-mern-with-docker-compose-4900156ba9dd#:~:text=For%20the%20dockerize%20a%20full,yml%20file.

# version: '3.8'

# Services
services:
  # Grid-Layout service
  grid-layout:
    build:
      context: ./grid-layout
      dockerfile: Dockerfile
    container_name: backend-grid-layout
    ports:
      - "8092:8092"
    env_file: ".env"
    depends_on:
      - mongodb

  # Grid-Themes service
  grid-themes:
    build:
      context: ./grid-themes
      dockerfile: Dockerfile
    container_name: backend-grid-themes
    ports:
      - "8082:8082"
    env_file: ".env"
    depends_on:
      - mongodb
  
  # Icon Proxy service
  icon-proxy:
    build:
      context: ./icon-proxy-server
      dockerfile: Dockerfile
    container_name: backend-icon-proxy
    ports:
      - "3000:3000"
    env_file: ".env"
    depends_on:
      - mongodb

  # Client service
  client:
    build:
      context: ./react-grid-vite-test1
      dockerfile: Dockerfile

    container_name: frontend
    ports:
      - "80:80"
    env_file: ".env"
    depends_on:
      - grid-layout
      - grid-themes
      - icon-proxy

  # Widget service
  widget:
    build:
      context: ./python-flask
      dockerfile: Dockerfile
      
    container_name: python-flask
    ports:
      - "3001:3001"
    env_file: ".env"
    depends_on:
      - mongodb

  # Database service
  mongodb:
    image: mongo:latest
    container_name: mongodb_server

    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DEV_MONGODB_PASSWORD}

    ports:
      - "27017:27017"

    volumes:
      - ./data:/data/db

# Volumes define
# volumes: 
#   mydata: