apiVersion: v1
kind: Service
metadata:
  name: grid-client-service
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  namespace: icon-portal-namespace
spec:
  type: ClusterIP
  selector:
    app: grid-client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80