apiVersion: v1
kind: Service
metadata:
  name: grid-themes-service
  namespace: icon-portal-namespace
spec:
  selector:
    app: grid-themes
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082