apiVersion: v1
kind: Service
metadata:
  name: icon-proxy-server-service
  namespace: icon-portal-namespace
spec:
  selector:
    app: icon-proxy-server
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000