name: build and deploy to google kubernetes engine

on:
  push:
    branches:
    - 'main'
    paths: 
    - 'react-grid-vite-test1/**'
    - 'grid-layout/**'

jobs:
  integrate: 
    runs-on: ubuntu-latest
    steps: 
      - name: code checkout
        uses: actions/checkout@v4  

      - name: nodejs setup
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.2'

      - name: install dependencies and run lint on react-grid-vite-test1 
        run: |
          cd react-grid-vite-test1
          npm install
          npm run lint
      
      - name: install dependencies and run unit/integration test on grid-layout
        run: |
          cd ../grid-layout 
          npm install
          npm run test

  deploy:
    needs: integrate
    runs-on: ubuntu-latest
    steps:

    - name: code checkout
      uses: actions/checkout@v4

    - id: 'auth'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        install_components: 'gke-gcloud-auth-plugin'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

    - name: build and push the docker image
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build -t us-central1-docker.pkg.dev/$GOOGLE_PROJECT/icon-portal-images/grid-thing-client:latest ./react-grid-vite-test1
        docker push us-central1-docker.pkg.dev/$GOOGLE_PROJECT/icon-portal-images/grid-thing-client:latest

    - name: deploy to gke
      env:
        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
      run: |
        gcloud container clusters get-credentials icon-portal-cluster --region us-central1
        sed -i "s/GOOGLE_PROJECT/$GOOGLE_PROJECT/g" ./kubernetes/grid-client.yaml
        kubectl delete deployment grid-client-deployment
        kubectl apply -f ./kubernetes/grid-client.yaml
